alter table VABANQUE_TRANSACTION add constraint FK_VABANQUE_TRANSACTION_ON_TO foreign key (TO_ID) references VABANQUE_ACCOUNT(ID);
create index IDX_VABANQUE_TRANSACTION_ON_TO on VABANQUE_TRANSACTION (TO_ID);
